<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>uploadResumeBox</name>
   <tag></tag>
   <elementGuidId>431ab32b-56d3-41b0-b190-50e50e5a8e99</elementGuidId>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App_app_1PX04&quot;]/div[@class=&quot;App_app-right-side_8Fr2V&quot;]/div[@class=&quot;App_app-contents_1ViAH&quot;]/div[1]/div[@class=&quot;QuestList_quest-list-container_28mlt&quot;]/div[@class=&quot;QuestList_quest-list-bg_1CH5p&quot;]/div[@class=&quot;QuestList_quest-list_2_Sjz&quot;]/div[@class=&quot;QuestList_quest-list-inner_4pmTa&quot;]/div[@class=&quot;Quest_quest-container_1XvLK&quot;]/div[@class=&quot;Quest_quest-container-2_23ZcB&quot;]/div[2]/div[@class=&quot;Quest_collapsible-area_1Ir2x&quot;]/div[2]/a[@class=&quot;Quest_clickable-area_2OFSd&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/student/quest/upload-resume/</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Quest_clickable-area_2OFSd</value>
   </webElementProperties>
</WebElementEntity>
