<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>2nd</name>
   <tag></tag>
   <elementGuidId>579bf599-76ea-4899-8f23-63436d846c00</elementGuidId>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App_app_1PX04&quot;]/div[@class=&quot;App_app-right-side_8Fr2V&quot;]/div[@class=&quot;App_app-contents_1ViAH&quot;]/div[1]/div[@class=&quot;DetailPreferencesQuestInterests_view-container_3Hvb6&quot;]/div[@class=&quot;HierarchyPreference_hierarchy-boxes_GO_j8&quot;]/div[@class=&quot;HierarchyPreference_box_qhNgh&quot;]/div[@class=&quot;HierarchyPreference_box-select-container_wamsE&quot;]/div[@class=&quot;Select_select-container_1iSnI&quot;]/div[@class=&quot;Select_select_570Kd&quot;]/div[@class=&quot;Select_field--container_Flhwj&quot;]/div[@class=&quot;Select_field_eQ2-s&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Select_field_eQ2-s</value>
   </webElementProperties>
</WebElementEntity>
