<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Select_select_570Kd (1)</name>
   <tag></tag>
   <elementGuidId>c1375983-76ca-40f9-8fc7-d7e0ef626ef4</elementGuidId>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;Signup_signup_icMxn&quot;]/div[@class=&quot;Signup_contents_1E2Gy&quot;]/div[1]/div[@class=&quot;Signup_form-container_20c80&quot;]/div[1]/div[@class=&quot;Select_select-container_1iSnI&quot;]/div[@class=&quot;Select_select_570Kd&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Select_select_570Kd</value>
   </webElementProperties>
</WebElementEntity>
