<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Select_field_eQ2-s (1)</name>
   <tag></tag>
   <elementGuidId>3956e860-1a1b-4a7e-93fd-0dcbc70641bd</elementGuidId>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;Signup_signup_icMxn&quot;]/div[@class=&quot;Signup_contents_1E2Gy&quot;]/div[1]/div[@class=&quot;Signup_form-container_20c80&quot;]/div[1]/div[@class=&quot;Select_select-container_1iSnI&quot;]/div[@class=&quot;Select_select_570Kd&quot;]/div[@class=&quot;Select_field--container_Flhwj&quot;]/div[@class=&quot;Select_field_eQ2-s&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Select_field_eQ2-s</value>
   </webElementProperties>
</WebElementEntity>
