<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Switchbox_switch-inner_ip</name>
   <tag></tag>
   <elementGuidId>b216339d-21d1-4521-aa59-b45d8826ad37</elementGuidId>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;Signup_signup_icMxn&quot;]/div[@class=&quot;Signup_contents_1E2Gy&quot;]/div[1]/div[@class=&quot;Signup_form-container--withGrid_u2q-T Signup_form-container_20c80&quot;]/div[@class=&quot;ProfileTermAvailability_term-availability-container_2ZQyn&quot;]/div[@class=&quot;ProfileTermAvailability_term-availability-box_4b_Fa&quot;]/div[@class=&quot;ProfileTermAvailability_term-availability-switchbox_vjTgW&quot;]/div[@class=&quot;Switchbox_switch-container_6VPUe&quot;]/label[@class=&quot;Switchbox_switch-label_1vetA&quot;]/span[@class=&quot;Switchbox_switch-inner_ipkar&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Switchbox_switch-inner_ipkar</value>
   </webElementProperties>
</WebElementEntity>
